### ISSUE TITLE
Would it be appropriate to use Resque::Scheduler for requeueing?

### ISSUE THREAD

**Issue by theSteveMitchell** [bartolsthoorn/resque-workers-lock#7]
In my domain I use Whenever to spawn a list of about 20 resque jobs every 15 minutes.  Most of those jobs finish in <5 seconds, but there are 1 or 2 that can take much longer (anywhere from 30 seconds to 2 hours) There are a couple issues I'm having with this code and the way it requeues jobs.  Let's say I have just enqueued all 20 jobs, and all of them are completed, except My::LongJob.  It is still being processed, and will take 2 more hours.  I have 4 workers total, and 3 are idle.  15 minutes later, those same 20 jobs are each queued again.

```ruby 
...
else
  sleep(requeue_perform_delay)
  Resque.enqueue(self, *args)
  raise Resque::Job::DontPerform
end
```

1. If I leave the requeue_perform_delay at the default 1 sec, when the other jobs finish, My::LongJob 2 will continually be picked up by the free worker, which will check the lock, pause 1 sec, and then requeue.  If I watch the stats in resque it'll add these jobs to the "processing" count, so that number will go up at the rate of 1/sec, even though they are just failing/requeuing.

2. If I set the perform delay higher, like 60 seconds, then the worker will be blocked while it sleeps.  This means that when I requeue the other shorter jobs, they need to wait for the worker to finish the delay.  If I had 2 different jobs that each took a long time, I might have 4 workers blocked on these 2 jobs, so any other faster jobs would wait in the queue for up to a minute. 

So, would it be appropriate to interrogate Resque::Scheduler, and if it's present queue the job up for a later time?  Something like:

```ruby
if Resque.redis.msetnx lock_result.zip([true]*lock_result.size).flatten
  lock_result.each do |lock|
    Resque.redis.expire(lock, worker_lock_timeout(*args))
  end
else
  if defined? Resque::Scheduler
    Resque.enqueue_in(requeue_perform_delay, self, *args) # run a job in 5 days
  else
    sleep(requeue_perform_delay)
    Resque.enqueue(self, *args)
  end  
  raise Resque::Job::DontPerform
end
```

This would offload the sleep onto the scheduler process, instead of the workers.  Happy to PR this, but wanted to get some thoughts first.

**Comment by bartolsthoorn** [comment]
Interesting problem, and thanks for taking the time set it out it so clearly!

I agree that workers with `self.requeue_perform_delay` should not be sleeping and instead take other jobs. It is better to use `Resque.enqueue_in` instead of `sleep`.

Secondly, even when `enqueue_in` is used, the _processing count_ will go up, because you will not be always be able to estimate the minimum amount of delay required. It could be possible to ignore jobs that issued a `Job::DontPerform` in `before_perform` in the statistics, but I guess it is not important to everyone. It could also be helpful to see the processing count go up as long as you know what caused it. It is probably best to keep the code as simple as possible and just interrogate Resque::Scheduler like you suggested.

Looking forward to the PR!

**Comment by bartolsthoorn** [comment]
@theSteveMitchell
Just checking in, did you have time to take a look at this?

**Comment by theSteveMitchell** [comment]
Thanks for the reminder!  Yes I tried the approach and it seems to work, the code is very easy but the tests are hard :frowning: Give me another week or two for a PR :smile:

**Comment by bartolsthoorn** [comment]
Ok, thank you! :+1:

**Comment by bogdanovich** [comment]
+1 for this feature to be incorporated

**Comment by bartolsthoorn** [comment]
Closed because @bogdanovich added this: https://github.com/bartolsthoorn/resque-workers-lock/pull/9
